
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  NodeCount = 2
  (1..NodeCount).each do |i|
    config.vm.define "centos8-#{i}" do |centos|
      centos.vm.box = "centos/8"
      centos.vm.box_version = "1905.1"
      centos.vm.hostname = "centos8-#{i}"
      centos.vm.network "public_network", ip: "192.168.1.16#{i}"
      centos.vm.provider "virtualbox" do |v|
        v.name = "centos8-#{i}"
        v.memory = 2048
        v.cpus = 2
        end
      end
    end
end
